inputs:
  production-deployment-environment:
    description: 'GitHubのDeployment Environmentに表示される名前'
    required: true
  production-branch:
    description: 'Productionデプロイ対象になるブランチ名'
    required: true
  publish-dir:
    description: 'Netlifyにデプロイするディレクトリ'
    required: true
  netlify-site-id:
    description: 'デプロイ先のNetlify ID'
    required: true
  GITHUB_TOKEN:
    required: true
  NETLIFY_AUTH_TOKEN:
    description: 'Netlifyへデプロイするためのトークン'
    required: true

runs:
  using: 'Composite'
  steps:
    - name: Set GitHub Deployment Environment
      id: github_deployment_environment
      run: |
        if [ "$GITHUB_EVENT_NAME" = "push" ]; then
          if [ "$GITHUB_REF_NAME" = "${{ inputs.production-branch }}" ]; then
            echo "GITHUB_DEPLOYMENT_ENVIRONMENT=${{ inputs.production-deployment-environment }}" >> $GITHUB_OUTPUT
          else
            echo "GITHUB_DEPLOYMENT_ENVIRONMENT=Netlify Branch $GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          fi
        else
          echo "GITHUB_DEPLOYMENT_ENVIRONMENT=Netlify Preview" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Set Netlify Alias
      id: netlify_alias
      run: |
        if [ "$GITHUB_EVENT_NAME" = "push" ]; then
          echo "ALIAS=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
        else
          echo "ALIAS=deploy-preview-${{ github.event.number }}" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: ${{ inputs.publish-dir }}
        production-branch: ${{ inputs.production-branch }}
        github-deployment-environment: ${{ steps.github_deployment_environment.outputs.GITHUB_DEPLOYMENT_ENVIRONMENT }}
        github-token: ${{ inputs.GITHUB_TOKEN }}
        deploy-message: ${{ github.event.head_commit.message || github.event.pull_request.title }}
        alias: ${{ steps.netlify_alias.outputs.ALIAS }}
        # enable-commit-comment: false
        # enable-commit-status: false
        fails-without-credentials: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ inputs.netlify-site-id }}
